import { api } from './platform';

type Service = { id:string; name:string; category:string; country?:string; governorate:string; city:string; description:string; phone:string; whatsapp?:string; premium?:boolean; featured?:boolean; providerName:string; providerEmail?:string; providerExperience?:string; rating?:number; reviewsCount?:number; viewsCount?:number; active:boolean; verified?:boolean };

const KEY='khidma-requests';
type RequestItem={id:string;title:string;category:string;location:string;budget:string;time:string;createdAt:string;status:'open'|'closed'};
const readRequests=():RequestItem[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const saveRequests=(x:RequestItem[])=>localStorage.setItem(KEY,JSON.stringify(x));

function trustScore(s:Service){let score=30;if(s.rating)score+=Math.min(25,s.rating*5);if((s.reviewsCount||0)>0)score+=Math.min(15,(s.reviewsCount||0)*1.5);if(s.providerExperience)score+=10;if(s.phone)score+=5;if(s.premium||s.featured)score+=10;if(s.verified)score+=5;return Math.min(100,Math.round(score));}
function availability(s:Service){const h=new Date().getHours();if(!s.active)return'غير متاح';return h>=8&&h<22?'متاح الآن':'خارج أوقات العمل';}
function smartParse(q:string){const normalized=q.toLowerCase().replace(/[،,]/g,' ');const cats=['كهربائي','سباك','نجار','ميكانيكي','مصلح هواتف','دهان','تنظيف','حلاق','مصور','دروس خصوصية','نقل','تكييف وتبريد','صيانة منزلية'];const cat=cats.find(x=>normalized.includes(x))||'';const gov=['تونس','أريانة','بن عروس','منوبة','نابل','زغوان','بنزرت','باجة','جندوبة','الكاف','سليانة','سوسة','المنستير','المهدية','صفاقس','القيروان','القصرين','سيدي بوزيد','قابس','مدنين','تطاوين','قفصة','توزر','قبلي'].find(x=>normalized.includes(x))||'';const city=(q.match(/(?:في|بـ|ب)\s+([\u0600-\u06FF\w-]{3,})/i)||[])[1]||'';return{cat,gov,city};}

function injectStyle(){if(document.getElementById('advanced-style'))return;const s=document.createElement('style');s.id='advanced-style';s.textContent=`.kx-fab{position:fixed;left:22px;bottom:22px;z-index:9999;border:0;border-radius:999px;padding:13px 18px;background:linear-gradient(135deg,#2563eb,#06b6d4);color:#fff;font-weight:900;box-shadow:0 12px 30px #0004;cursor:pointer}.kx-panel{position:fixed;left:22px;bottom:78px;width:min(420px,calc(100vw - 44px));max-height:78vh;overflow:auto;z-index:10000;background:#07111f;color:#fff;border:1px solid #ffffff22;border-radius:22px;padding:20px;box-shadow:0 25px 70px #0008;direction:rtl}.kx-panel h3{margin:0 0 6px}.kx-panel p{color:#b8c5d9}.kx-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.kx-panel input,.kx-panel select,.kx-panel textarea{width:100%;box-sizing:border-box;background:#0e1b2c;color:#fff;border:1px solid #ffffff1c;border-radius:12px;padding:11px;margin:5px 0}.kx-panel textarea{min-height:80px}.kx-btn{border:0;border-radius:12px;padding:11px 14px;font-weight:800;cursor:pointer;margin-top:8px}.kx-primary{background:#2563eb;color:#fff}.kx-soft{background:#ffffff12;color:#fff}.kx-close{float:left;background:none;border:0;color:#fff;font-size:22px;cursor:pointer}.kx-score{display:inline-block;padding:4px 8px;border-radius:99px;background:#16a34a22;color:#5ee89a;font-weight:900}.kx-card{padding:12px;margin:8px 0;border:1px solid #ffffff12;border-radius:14px;background:#ffffff06}.kx-tag{display:inline-block;font-size:12px;padding:4px 7px;border-radius:8px;background:#2563eb22;color:#8eb7ff;margin:3px}.kx-request{border-top:1px solid #ffffff12;margin-top:14px;padding-top:14px}`;document.head.appendChild(s)}

async function getServices():Promise<Service[]>{try{const r=await api.get('/api/services');const data=r.data as {services?:unknown};return Array.isArray(data.services)?data.services as Service[]:[]}catch{return[]}}
function esc(v:string){return v.replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]||c))}

function panel(){if(document.getElementById('kx-panel'))return;const p=document.createElement('div');p.id='kx-panel';p.className='kx-panel';p.innerHTML=`<button class="kx-close" id="kx-close" aria-label="إغلاق">×</button><h3>خِدمة الذكية ⚡</h3><p>ابحث بطريقة طبيعية أو اطلب خدمة وسنرتب لك الخيارات.</p><input id="kx-smart" aria-label="البحث الذكي" placeholder="مثال: أحتاج كهربائي في صفاقس اليوم"><button class="kx-btn kx-primary" id="kx-search">بحث ذكي</button><div id="kx-results"></div><div class="kx-request"><h3>اطلب خدمة</h3><div class="kx-grid"><input id="kr-title" placeholder="ما الذي تحتاجه؟"><input id="kr-cat" placeholder="الفئة"></div><div class="kx-grid"><input id="kr-loc" placeholder="المدينة / المنطقة"><input id="kr-budget" placeholder="الميزانية التقريبية"></div><input id="kr-time" placeholder="متى تحتاجها؟"><textarea id="kr-note" placeholder="تفاصيل الطلب"></textarea><button class="kx-btn kx-primary" id="kr-send">حفظ طلب الخدمة</button></div><div class="kx-request" id="kx-dashboard"></div>`;document.body.appendChild(p);document.getElementById('kx-close')!.addEventListener('click',()=>p.remove());document.getElementById('kx-search')!.addEventListener('click',async()=>{const q=(document.getElementById('kx-smart') as HTMLInputElement).value.trim();const parsed=smartParse(q);const list=(await getServices()).filter(s=>s.active&&(!parsed.cat||s.category===parsed.cat)&&(!parsed.gov||s.governorate===parsed.gov)&&(!parsed.city||s.city.includes(parsed.city))).sort((a,b)=>trustScore(b)-trustScore(a));const out=document.getElementById('kx-results')!;out.innerHTML=list.length?`<h3>أفضل النتائج</h3>${list.slice(0,8).map(s=>`<div class="kx-card"><b>${esc(s.name)}</b><br><span class="kx-tag">${esc(s.category)}</span><span class="kx-tag">${esc(s.city)}</span><span class="kx-tag">${availability(s)}</span><br><small>الثقة <span class="kx-score">${trustScore(s)}/100</span> · ${s.rating?s.rating.toFixed(1):'جديد'} ⭐ · ${s.reviewsCount||0} تقييم ${s.verified?'· ✓ موثّق':''}</small><br><a href="tel:${esc(s.phone)}" class="kx-btn kx-primary" style="display:inline-block;text-decoration:none">اتصال</a></div>`).join('')}`:'<div class="kx-card">لم نجد تطابقًا دقيقًا. جرّب اسم الفئة والمدينة.</div>'});document.getElementById('kr-send')!.addEventListener('click',()=>{const title=(document.getElementById('kr-title') as HTMLInputElement).value.trim();if(!title){alert('اكتب الخدمة المطلوبة أولًا');return}const items=readRequests();items.unshift({id:crypto.randomUUID(),title,category:(document.getElementById('kr-cat') as HTMLInputElement).value.trim(),location:(document.getElementById('kr-loc') as HTMLInputElement).value.trim(),budget:(document.getElementById('kr-budget') as HTMLInputElement).value.trim(),time:(document.getElementById('kr-time') as HTMLInputElement).value.trim(),createdAt:new Date().toISOString(),status:'open'});saveRequests(items);alert('تم حفظ طلبك على هذا الجهاز.');renderDashboard()});renderDashboard()}
function renderDashboard(){const el=document.getElementById('kx-dashboard');if(!el)return;const req=readRequests();el.innerHTML=`<h3>لوحة سريعة</h3><div class="kx-grid"><div class="kx-card"><b>${req.filter(x=>x.status==='open').length}</b><br><small>طلبات مفتوحة</small></div><div class="kx-card"><b>${req.length}</b><br><small>إجمالي الطلبات</small></div></div>${req.slice(0,3).map(x=>`<div class="kx-card"><b>${esc(x.title)}</b><br><small>${esc(x.location||'كل المناطق')} · ${esc(x.time||'مرن')}</small></div>`).join('')}`}

function addTrustBadges(){document.querySelectorAll<HTMLElement>('.service-card').forEach(card=>{if(card.querySelector('.kx-enhanced'))return;const id=card.dataset.open;if(!id)return;const badge=document.createElement('span');badge.className='kx-enhanced kx-tag';badge.textContent='✓ تحسينات خِدمة';const rating=card.querySelector('.rating');rating?.appendChild(badge)});}
function addFab(){if(document.getElementById('kx-fab'))return;const b=document.createElement('button');b.id='kx-fab';b.className='kx-fab';b.textContent='⚡ خِدمة الذكية';b.setAttribute('aria-label','فتح خِدمة الذكية');b.addEventListener('click',panel);document.body.appendChild(b)}
function enhance(){injectStyle();addFab();addTrustBadges()}
new MutationObserver(()=>{if(document.body)enhance()}).observe(document.documentElement,{childList:true,subtree:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
