import type { VercelRequest, VercelResponse } from '@vercel/node';
import { createClient, type User } from '@supabase/supabase-js';

const url = process.env.SUPABASE_URL!;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const supabase = createClient(url, serviceKey, { auth: { persistSession: false, autoRefreshToken: false } });
const BUCKET = process.env.SUPABASE_STORAGE_BUCKET || 'haja-naar';
const ADMIN_EMAILS = ['amirkotti51@gmail.com'];
const clean = (v: unknown) => String(v ?? '').trim();
const json = (res: VercelResponse, status: number, body: unknown) => res.status(status).setHeader('Content-Type', 'application/json; charset=utf-8').json(body);
const error = (res: VercelResponse, message: string, status = 400) => json(res, status, { error: message });
const bodyOf = (req: VercelRequest) => typeof req.body === 'object' && req.body ? req.body as Record<string, unknown> : {};

async function rows<T>(table: string) { const { data, error: e } = await supabase.from(table).select('*').range(0, 9999); if (e) throw e; return (data || []) as T[]; }
async function one<T>(table: string, id: string) { const { data, error: e } = await supabase.from(table).select('*').eq('id', id).maybeSingle(); if (e) throw e; return data as T | null; }
async function add<T extends Record<string, unknown>>(table: string, record: T) { const { data, error: e } = await supabase.from(table).insert(record).select('id').single(); if (e) throw e; return data?.id as string; }
async function update(table: string, id: string, record: Record<string, unknown>) { const { error: e } = await supabase.from(table).update(record).eq('id', id); if (e) throw e; }
async function remove(table: string, id: string) { const { error: e } = await supabase.from(table).delete().eq('id', id); if (e) throw e; }

interface ServiceRecord { id: string; providerId: string; providerName: string; providerEmail?: string; providerBio?: string; providerExperience?: string; providerPhoto?: string; name: string; category: string; country?: string; governorate: string; city: string; description: string; price?: string; phone: string; whatsapp?: string; hours?: string; portfolio?: string[]; active: boolean; premium?: boolean; featured?: boolean; expiresAt?: string; createdAt: string }
interface ReviewRecord { id: string; serviceId: string; userId: string; userName: string; rating: number; comment: string; createdAt: string }
interface ViewRecord { id: string; serviceId: string; createdAt: string }
interface VerificationRecord { id: string; providerId: string; providerName: string; email?: string; status: string; createdAt: string }
interface PremiumRequest { id: string; serviceId: string; providerId: string; providerName: string; status: 'pending' | 'approved' | 'rejected'; createdAt: string; reviewedAt?: string }
interface PremiumOrder { id: string; serviceId: string; providerId: string; providerName: string; plan: 'weekly' | 'monthly' | 'quarterly'; price: number; days: number; status: 'pending' | 'paid' | 'rejected'; createdAt: string; paidAt?: string; expiresAt?: string; paymentRef?: string; payUrl?: string; orderId?: string }

async function getUser(req: VercelRequest): Promise<User | null> {
  const auth = clean(req.headers.authorization);
  if (!auth.toLowerCase().startsWith('bearer ')) return null;
  const token = auth.slice(7).trim();
  if (!token) return null;
  const { data, error: e } = await supabase.auth.getUser(token);
  if (e || !data.user) return null;
  return data.user;
}
async function requireUser(req: VercelRequest, res: VercelResponse) { const user = await getUser(req); if (!user) { error(res, 'يجب تسجيل الدخول', 401); return null; } return user; }
async function requireAdmin(req: VercelRequest, res: VercelResponse) { const user = await requireUser(req, res); if (!user) return null; if (!ADMIN_EMAILS.includes(user.email || '')) { error(res, 'غير مصرح', 403); return null; } return user; }
async function listServices() { const all = await rows<ServiceRecord>('services'); const now = Date.now(); return all.sort((a,b) => { const ap = Boolean((a.featured || a.premium) && (!a.expiresAt || new Date(a.expiresAt).getTime() > now)); const bp = Boolean((b.featured || b.premium) && (!b.expiresAt || new Date(b.expiresAt).getTime() > now)); return Number(bp)-Number(ap) || b.createdAt.localeCompare(a.createdAt); }); }
async function serviceStats(serviceId: string) { const [reviews, views] = await Promise.all([rows<ReviewRecord>('service_reviews'), rows<ViewRecord>('service_views')]); const r=reviews.filter(x=>x.serviceId===serviceId); return { rating:r.length?Math.round((r.reduce((n,x)=>n+x.rating,0)/r.length)*10)/10:0, reviewsCount:r.length, viewsCount:views.filter(x=>x.serviceId===serviceId).length }; }
async function storageUrl(path: string) { const { data } = supabase.storage.from(BUCKET).getPublicUrl(path); return data.publicUrl || ''; }
function decodeBase64(data: string) { const base64=data.includes(',')?data.split(',').pop()||'':data; return Buffer.from(base64,'base64'); }

export default async function handler(req: VercelRequest, res: VercelResponse) {
  try {
    const path = '/' + (Array.isArray(req.query.path) ? req.query.path.join('/') : clean(req.query.path));
    const method = req.method || 'GET';
    if (method==='GET' && path==='/api/_healthcheck') return json(res,200,{message:'Success'});
    if (method==='GET' && path==='/api/services') { const all=await listServices(); const services=await Promise.all(all.filter(s=>s.active).map(async s=>({...s,...await serviceStats(s.id)}))); return json(res,200,{services}); }
    const serviceMatch=path.match(/^\/api\/services\/([^/]+)$/); const serviceId=serviceMatch?.[1] ? decodeURIComponent(serviceMatch[1]) : '';
    if (method==='GET' && serviceId) { const s=await one<ServiceRecord>('services',serviceId); if(!s||!s.active)return error(res,'الخدمة غير موجودة',404); return json(res,200,{service:{...s,...await serviceStats(serviceId)}}); }
    const viewMatch=path.match(/^\/api\/services\/([^/]+)\/view$/); if(method==='POST'&&viewMatch){const id=decodeURIComponent(viewMatch[1]);const s=await one<ServiceRecord>('services',id);if(!s||!s.active)return error(res,'الخدمة غير موجودة',404);await add('service_views',{serviceId:id,createdAt:new Date().toISOString()});return json(res,200,{ok:true});}
    const portfolioMatch=path.match(/^\/api\/services\/([^/]+)\/portfolio$/);
    if(method==='GET'&&portfolioMatch){const id=decodeURIComponent(portfolioMatch[1]);const s=await one<ServiceRecord>('services',id);if(!s||!s.active)return error(res,'الخدمة غير موجودة',404);const paths=(s.portfolio||[]).filter(v=>v.startsWith('storage:')).map(v=>v.slice(8));return json(res,200,{urls:await Promise.all(paths.map(storageUrl)),count:(s.portfolio||[]).length});}
    if(method==='POST'&&portfolioMatch){const user=await requireUser(req,res);if(!user)return;const id=decodeURIComponent(portfolioMatch[1]);const s=await one<ServiceRecord>('services',id);if(!s||s.providerId!==user.id)return error(res,'الخدمة غير موجودة أو غير مصرح بها',404);const files=Array.isArray(bodyOf(req).files)?(bodyOf(req).files as Array<{data?:string;contentType?:string}>).slice(0,6):[];if(!files.length)return error(res,'لم يتم إرسال صور');const existing=(s.portfolio||[]).filter(v=>v.startsWith('storage:'));if(existing.length+files.length>6)return error(res,'الحد الأقصى 6 صور لكل خدمة');const paths:string[]=[];for(let i=0;i<files.length;i++){const ct=clean(files[i].contentType);if(!['image/jpeg','image/png','image/webp'].includes(ct))return error(res,'صيغة الصورة غير مدعومة');const data=clean(files[i].data);if(!data||data.length>4500000)return error(res,'حجم إحدى الصور كبير جداً');const ext=ct==='image/png'?'png':ct==='image/webp'?'webp':'jpg';const p=`portfolio/${id}/${Date.now()}-${i}-${Math.random().toString(36).slice(2,8)}.${ext}`;const {error:e}=await supabase.storage.from(BUCKET).upload(p,decodeBase64(data),{contentType:ct,upsert:false});if(e)return error(res,'تعذر حفظ بعض الصور',500);paths.push(p);}const portfolio=[...existing,...paths.map(p=>`storage:${p}`)].slice(0,6);await update('services',id,{portfolio});return json(res,200,{ok:true,count:portfolio.length,urls:await Promise.all(paths.map(storageUrl))});}
    if(method==='GET'&&path==='/api/my-services'){const user=await requireUser(req,res);if(!user)return;return json(res,200,{services:(await listServices()).filter(s=>s.providerId===user.id)});}
    if(method==='GET'&&path==='/api/my-profile'){const user=await requireUser(req,res);if(!user)return;const first=(await listServices()).find(s=>s.providerId===user.id);const photoUrl=first?.providerPhoto?.startsWith('storage:')?await storageUrl(first.providerPhoto.slice(8)):'';return json(res,200,{photoUrl});}
    if(method==='PUT'&&path==='/api/my-profile'){const user=await requireUser(req,res);if(!user)return;const b=bodyOf(req);const bio=clean(b.bio).slice(0,600),experience=clean(b.experience).slice(0,80);const mine=(await listServices()).filter(s=>s.providerId===user.id);if(!mine.length)return error(res,'أضف خدمة واحدة على الأقل قبل إنشاء ملفك المهني');for(const s of mine)await update('services',s.id,{providerBio:bio,providerExperience:experience});return json(res,200,{ok:true,bio,experience});}
    if(method==='POST'&&path==='/api/provider/photo'){const user=await requireUser(req,res);if(!user)return;const b=bodyOf(req),ct=clean(b.contentType),data=clean(b.data);if(!['image/jpeg','image/png','image/webp'].includes(ct))return error(res,'صيغة الصورة غير مدعومة');if(!data||data.length>4500000)return error(res,'حجم الصورة كبير جداً');const ext=ct==='image/png'?'png':ct==='image/webp'?'webp':'jpg';const p=`providers/${user.id}/profile.${ext}`;const {error:e}=await supabase.storage.from(BUCKET).upload(p,decodeBase64(data),{contentType:ct,upsert:true});if(e)return error(res,'تعذر حفظ الصورة',500);const mine=(await listServices()).filter(s=>s.providerId===user.id);if(!mine.length)return error(res,'أضف خدمة أولاً');for(const s of mine)await update('services',s.id,{providerPhoto:`storage:${p}`});return json(res,200,{ok:true,url:await storageUrl(p)});}
    if(method==='POST'&&path==='/api/services'){const user=await requireUser(req,res);if(!user)return;const b=bodyOf(req);const name=clean(b.name),category=clean(b.category),governorate=clean(b.governorate),city=clean(b.city),description=clean(b.description),phone=clean(b.phone);if(!name||!category||!governorate||!city||description.length<10||description.length>1200||!phone)return error(res,'أكمل بيانات الخدمة بشكل صحيح');if(!/^[0-9+ ()-]{7,25}$/.test(phone))return error(res,'رقم الهاتف غير صالح');const record={providerId:user.id,providerName:String(user.user_metadata?.full_name||user.user_metadata?.name||user.email?.split('@')[0]||'مقدّم خدمة'),providerEmail:user.email||'',providerBio:'',providerExperience:'',name,category,country:clean(b.country)||'تونس',governorate,city,description,price:clean(b.price).slice(0,100),hours:clean(b.hours).slice(0,100),phone,whatsapp:clean(b.whatsapp).slice(0,25),portfolio:Array.isArray(b.portfolio)?(b.portfolio as unknown[]).map(clean).filter(v=>/^https?:\/\//i.test(v)).slice(0,6):[],active:true,premium:false,featured:false,createdAt:new Date().toISOString()};const id=await add('services',record);return json(res,201,{id,service:{...record,id}});}
    if(method==='DELETE'&&serviceId){const user=await requireUser(req,res);if(!user)return;const s=await one<ServiceRecord>('services',serviceId);if(!s)return error(res,'الخدمة غير موجودة',404);if(s.providerId!==user.id)return error(res,'غير مصرح',403);await remove('services',serviceId);return json(res,200,{ok:true});}
    if(method==='POST'&&path==='/api/verification-requests'){const user=await requireUser(req,res);if(!user)return;const items=await rows<VerificationRecord>('verification_requests');if(items.some(v=>v.providerId===user.id&&v.status==='pending'))return error(res,'لديك طلب تحقق قيد المراجعة',409);const id=await add('verification_requests',{providerId:user.id,providerName:String(user.user_metadata?.full_name||user.email||'مقدم خدمة'),email:user.email||'',status:'pending',createdAt:new Date().toISOString()});return json(res,201,{ok:true,id});}
    if(method==='GET'&&path==='/api/my-verification'){const user=await requireUser(req,res);if(!user)return;const rowsV=(await rows<VerificationRecord>('verification_requests')).filter(v=>v.providerId===user.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return json(res,200,{request:rowsV[0]||null});}
    if(method==='POST'&&path==='/api/premium-orders'){const user=await requireUser(req,res);if(!user)return;const b=bodyOf(req),sid=clean(b.serviceId),plan=clean(b.plan);const plans:Record<string,{price:number;days:number}>={weekly:{price:5,days:7},monthly:{price:15,days:30},quarterly:{price:35,days:90}};const selected=plans[plan];const s=await one<ServiceRecord>('services',sid);if(!s||s.providerId!==user.id)return error(res,'الخدمة غير موجودة أو غير مصرح بها',404);if(s.premium||s.featured)return error(res,'هذه الخدمة مميزة بالفعل',409);if(!selected)return error(res,'الخطة غير صالحة');if(!process.env.KONNECT_API_KEY||!process.env.KONNECT_WALLET_ID)return error(res,'الدفع الإلكتروني غير مهيأ بعد',503);const existing=await rows<PremiumOrder>('premium_orders');if(existing.some(o=>o.serviceId===sid&&o.status==='pending'))return error(res,'لديك عملية دفع قيد التنفيذ',409);const orderId=`KT-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const id=await add('premium_orders',{serviceId:sid,providerId:user.id,providerName:String(user.user_metadata?.full_name||s.providerName),plan,price:selected.price,days:selected.days,status:'pending',createdAt:new Date().toISOString(),orderId});try{const response=await fetch('https://api.konnect.network/api/v2/payments/init-payment',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':process.env.KONNECT_API_KEY},body:JSON.stringify({receiverWalletId:process.env.KONNECT_WALLET_ID,amount:selected.price*1000,token:'TND',type:'immediate',description:`ترويج خِدمة TN - ${plan}`,acceptedPaymentMethods:['bank_card','e-DINAR'],lifespan:30,checkoutForm:true,addPaymentFeesToAmount:false,orderId,webhook:`${originOf(req)}/api/konnect/webhook`,theme:'dark'})});if(!response.ok)throw new Error(`Konnect init failed: ${response.status}`);const payment=await response.json() as {payUrl?:string;paymentRef?:string};if(!payment.payUrl||!payment.paymentRef)throw new Error('Incomplete payment data');await update('premium_orders',id,{paymentRef:payment.paymentRef,payUrl:payment.payUrl});return json(res,201,{ok:true,id,price:selected.price,days:selected.days,paymentRef:payment.paymentRef,payUrl:payment.payUrl});}catch(e){console.error(e);await update('premium_orders',id,{status:'rejected'});return error(res,'تعذر إنشاء رابط الدفع الإلكتروني. حاول مرة أخرى.',502);}}
    if(method==='GET'&&path==='/api/konnect/webhook'){const paymentRef=clean(req.query.payment_ref);if(!paymentRef)return error(res,'payment_ref مطلوب');if(!process.env.KONNECT_API_KEY)return error(res,'الدفع الإلكتروني غير مهيأ',503);const order=(await rows<PremiumOrder>('premium_orders')).find(o=>o.paymentRef===paymentRef);if(!order)return error(res,'عملية الدفع غير معروفة',404);if(order.status==='paid')return json(res,200,{ok:true,alreadyProcessed:true});try{const response=await fetch(`https://api.konnect.network/api/v2/payments/${encodeURIComponent(paymentRef)}`,{headers:{'x-api-key':process.env.KONNECT_API_KEY}});if(!response.ok)throw new Error('status failed');const payload=await response.json() as {payment?:{status?:string;amount?:number;token?:string;orderId?:string;transactions?:Array<{status?:string}>}};const p=payload.payment;const success=p?.transactions?.some(t=>t.status==='success'),amountOk=Number(p?.amount)===order.price*1000,currencyOk=p?.token==='TND',orderIdOk=!p?.orderId||p.orderId===order.orderId;if(p?.status!=='completed'||!success||!amountOk||!currencyOk||!orderIdOk)return json(res,200,{ok:true,paid:false});const s=await one<ServiceRecord>('services',order.serviceId);if(!s)return error(res,'الخدمة غير موجودة',404);const expiresAt=new Date(Date.now()+order.days*86400000).toISOString();await update('services',s.id,{premium:true,featured:true,expiresAt});await update('premium_orders',order.id,{status:'paid',paidAt:new Date().toISOString(),expiresAt});return json(res,200,{ok:true,paid:true,expiresAt});}catch(e){console.error(e);return error(res,'تعذر التحقق من الدفع',502);}}
    if(method==='GET'&&path==='/api/my-premium-orders'){const user=await requireUser(req,res);if(!user)return;return json(res,200,{orders:(await rows<PremiumOrder>('premium_orders')).filter(o=>o.providerId===user.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))});}
    const orderMatch=path.match(/^\/api\/premium-orders\/([^/]+)$/);if(method==='GET'&&orderMatch){const user=await requireUser(req,res);if(!user)return;const o=await one<PremiumOrder>('premium_orders',decodeURIComponent(orderMatch[1]));if(!o||o.providerId!==user.id)return error(res,'عملية الدفع غير موجودة',404);return json(res,200,{order:o});}
    if(method==='POST'&&path==='/api/premium-requests'){const user=await requireUser(req,res);if(!user)return;const sid=clean(bodyOf(req).serviceId),s=await one<ServiceRecord>('services',sid);if(!s||s.providerId!==user.id)return error(res,'الخدمة غير موجودة أو غير مصرح بها',404);if(s.premium||s.featured)return error(res,'هذه الخدمة مميزة بالفعل',409);const items=await rows<PremiumRequest>('premium_requests');if(items.some(r=>r.serviceId===sid&&r.status==='pending'))return error(res,'لديك طلب تمييز قيد المراجعة',409);const id=await add('premium_requests',{serviceId:sid,providerId:user.id,providerName:String(user.user_metadata?.full_name||s.providerName),status:'pending',createdAt:new Date().toISOString()});return json(res,201,{ok:true,id});}
    if(method==='GET'&&path==='/api/my-premium-requests'){const user=await requireUser(req,res);if(!user)return;return json(res,200,{requests:(await rows<PremiumRequest>('premium_requests')).filter(r=>r.providerId===user.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))});}
    if(method==='GET'&&path==='/api/reviews'){const sid=clean(req.query.serviceId);const reviews=(await rows<ReviewRecord>('service_reviews')).filter(r=>r.serviceId===sid).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return json(res,200,{reviews});}
    if(method==='POST'&&path==='/api/reviews'){const user=await requireUser(req,res);if(!user)return;const b=bodyOf(req),sid=clean(b.serviceId),comment=clean(b.comment),rating=Number(b.rating),s=await one<ServiceRecord>('services',sid);if(!s||!s.active)return error(res,'الخدمة غير موجودة',404);if(!sid||rating<1||rating>5||!comment||comment.length>500)return error(res,'التقييم غير صالح');const reviews=await rows<ReviewRecord>('service_reviews');if(reviews.some(r=>r.serviceId===sid&&r.userId===user.id))return error(res,'يمكنك تقييم الخدمة مرة واحدة فقط',409);const id=await add('service_reviews',{serviceId:sid,userId:user.id,userName:String(user.user_metadata?.full_name||user.email||'مستخدم'),rating:Math.round(rating),comment,createdAt:new Date().toISOString()});return json(res,201,{id});}
    if(method==='POST'&&path==='/api/reports'){const user=await requireUser(req,res);if(!user)return;const b=bodyOf(req),sid=clean(b.serviceId),reason=clean(b.reason);if(!sid||!reason||reason.length>500)return error(res,'بيانات البلاغ غير صالحة');const id=await add('service_reports',{serviceId:sid,reason,userId:user.id,createdAt:new Date().toISOString()});return json(res,201,{ok:true,id});}
    if(method==='GET'&&path==='/api/logo'){return json(res,200,{url:await storageUrl('branding/site-logo')||null});}
    if(method==='PUT'&&path==='/api/admin/logo'){const user=await requireAdmin(req,res);if(!user)return;const b=bodyOf(req),data=clean(b.data),ct=clean(b.contentType);if(!data||!['image/png','image/jpeg','image/webp','image/svg+xml'].includes(ct))return error(res,'صيغة الشعار غير مدعومة');if(data.length>3500000)return error(res,'حجم الشعار كبير جداً');const {error:e}=await supabase.storage.from(BUCKET).upload('branding/site-logo',decodeBase64(data),{contentType:ct,upsert:true});if(e)return error(res,'تعذر حفظ الشعار',500);return json(res,200,{ok:true,url:await storageUrl('branding/site-logo')});}
    if(method==='GET'&&path==='/api/admin/summary'){const user=await requireAdmin(req,res);if(!user)return;const [s,r,rep,v,ver,pr,po]=await Promise.all([rows<ServiceRecord>('services'),rows<ReviewRecord>('service_reviews'),rows<any>('service_reports'),rows<ViewRecord>('service_views'),rows<VerificationRecord>('verification_requests'),rows<PremiumRequest>('premium_requests'),rows<PremiumOrder>('premium_orders')]);const active=s.filter(x=>x.active),counts=new Map<string,number>();for(const x of v)counts.set(x.serviceId,(counts.get(x.serviceId)||0)+1);const top=active.sort((a,b)=>(counts.get(b.id)||0)-(counts.get(a.id)||0)).slice(0,5).map(x=>({id:x.id,name:x.name,providerName:x.providerName,viewsCount:counts.get(x.id)||0}));return json(res,200,{stats:{services:s.length,activeServices:active.length,reviews:r.length,reports:rep.length,views:v.length,pendingVerifications:ver.filter(x=>x.status==='pending').length,pendingPremium:pr.filter(x=>x.status==='pending').length,pendingPayments:po.filter(x=>x.status==='pending').length,paidOrders:po.filter(x=>x.status==='paid').length,revenue:po.filter(x=>x.status==='paid').reduce((sum,o)=>sum+Number(o.price),0)},top});}
    if(method==='GET'&&path==='/api/admin/services'){const user=await requireAdmin(req,res);if(!user)return;const all=await listServices();return json(res,200,{services:await Promise.all(all.map(async s=>({...s,...await serviceStats(s.id)})))});}
    const adminServiceMatch=path.match(/^\/api\/admin\/services\/([^/]+)$/);if(method==='PUT'&&adminServiceMatch){const user=await requireAdmin(req,res);if(!user)return;const id=decodeURIComponent(adminServiceMatch[1]),b=bodyOf(req),s=await one<ServiceRecord>('services',id);if(!s)return error(res,'الخدمة غير موجودة',404);const patch:Record<string,unknown>={};if(typeof b.active==='boolean')patch.active=b.active;if(typeof b.featured==='boolean')patch.featured=b.featured;if(typeof b.premium==='boolean')patch.premium=b.premium;if(!Object.keys(patch).length)return error(res,'بيانات التعديل غير صالحة');await update('services',id,patch);return json(res,200,{ok:true});}
    if(method==='GET'&&path==='/api/admin/reports'){const user=await requireAdmin(req,res);if(!user)return;const reports=await rows<any>('service_reports');return json(res,200,{reports:reports.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))});}
    const reportMatch=path.match(/^\/api\/admin\/reports\/([^/]+)$/);if(method==='DELETE'&&reportMatch){const user=await requireAdmin(req,res);if(!user)return;await remove('service_reports',decodeURIComponent(reportMatch[1]));return json(res,200,{ok:true});}
    if(method==='GET'&&path==='/api/admin/verifications'){const user=await requireAdmin(req,res);if(!user)return;const requests=await rows<VerificationRecord>('verification_requests');return json(res,200,{requests:requests.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))});}
    const verMatch=path.match(/^\/api\/admin\/verifications\/([^/]+)$/);if(method==='PUT'&&verMatch){const user=await requireAdmin(req,res);if(!user)return;const id=decodeURIComponent(verMatch[1]),status=clean(bodyOf(req).status);if(!['approved','rejected'].includes(status))return error(res,'حالة التحقق غير صالحة');const v=await one<VerificationRecord>('verification_requests',id);if(!v)return error(res,'طلب التحقق غير موجود',404);await update('verification_requests',id,{status});return json(res,200,{ok:true});}
    if(method==='DELETE'&&path.startsWith('/api/admin/reviews/')){const user=await requireAdmin(req,res);if(!user)return;await remove('service_reviews',decodeURIComponent(path.split('/').pop()!));return json(res,200,{ok:true});}
    if(method==='GET'&&path==='/api/admin/premium-orders'){const user=await requireAdmin(req,res);if(!user)return;const orders=await rows<PremiumOrder>('premium_orders');return json(res,200,{orders:orders.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))});}
    const adminOrder=path.match(/^\/api\/admin\/premium-orders\/([^/]+)$/);if(method==='PUT'&&adminOrder){const user=await requireAdmin(req,res);if(!user)return;const status=clean(bodyOf(req).status);if(status!=='rejected')return error(res,'التعديل اليدوي على الدفع غير متاح');const o=await one<PremiumOrder>('premium_orders',decodeURIComponent(adminOrder[1]));if(!o)return error(res,'طلب الدفع غير موجود',404);await update('premium_orders',o.id,{status});return json(res,200,{ok:true});}
    if(method==='GET'&&path==='/api/admin/premium-requests'){const user=await requireAdmin(req,res);if(!user)return;const requests=await rows<PremiumRequest>('premium_requests');return json(res,200,{requests:requests.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))});}
    const adminPremium=path.match(/^\/api\/admin\/premium-requests\/([^/]+)$/);if(method==='PUT'&&adminPremium){const user=await requireAdmin(req,res);if(!user)return;const id=decodeURIComponent(adminPremium[1]),status=clean(bodyOf(req).status);if(!['approved','rejected'].includes(status))return error(res,'حالة طلب التمييز غير صالحة');const r=await one<PremiumRequest>('premium_requests',id);if(!r)return error(res,'طلب التمييز غير موجود',404);const s=await one<ServiceRecord>('services',r.serviceId);if(!s)return error(res,'الخدمة غير موجودة',404);await update('premium_requests',id,{status,reviewedAt:new Date().toISOString()});if(status==='approved')await update('services',s.id,{premium:true,featured:true});return json(res,200,{ok:true});}
    if(method==='GET'&&path==='/robots.txt')return res.status(200).setHeader('Content-Type','text/plain; charset=utf-8').send(`User-agent: Googlebot\nAllow: /\n\nUser-agent: *\nAllow: /\n\nSitemap: ${originOf(req)}/sitemap.xml\n`);
    if(method==='GET'&&path==='/sitemap.xml'){const origin=originOf(req);const slugs=['tunis','ariana','ben-arous','manouba','nabeul','zaghouan','bizerte','beja','jendouba','kef','siliana','sousse','monastir','mahdia','sfax','kairouan','kasserine','sidi-bouzid','gabes','medenine','tataouine','gafsa','tozeur','kebili'];const urls=[origin,...slugs.map(s=>`${origin}/services/${s}`)];const xml='<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(u=>`<url><loc>${u}</loc></url>`).join('')+'</urlset>';return res.status(200).setHeader('Content-Type','application/xml; charset=utf-8').send(xml);}
    return error(res,'المسار غير موجود',404);
  } catch (e) { console.error(e); return error(res,'حدث خطأ في الخادم',500); }
}
function originOf(req: VercelRequest) { const proto=clean(req.headers['x-forwarded-proto'])||'https'; const host=clean(req.headers.host); return `${proto}://${host}`; }
